import os
import re
from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
import arabic_reshaper
from bidi.algorithm import get_display

class PDFGenerator:
    def __init__(self, job_dir: str, lang: str = 'ar'):
        self.job_dir = job_dir
        self.lang = lang
        self.font_path = "C:\\Windows\\Fonts\\arial.ttf"
        pdfmetrics.registerFont(TTFont('Arabic', self.font_path))
        
        self.texts = {
            'ar': {
                'republic': "الجمهورية الجزائرية الديمقراطية الشعبية",
                'ministry': "وزارة التربية الوطنية",
                'teacher_title': "جدول توقيت الأستاذ:",
                'class_title': "جدول توقيت القسم:",
                'season': "الموسم الدراسي: 2026 - 2027",
                'days': ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس"],
                'headers': ["الأيام", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00"],
                'footer': "تم التوليد آلياً عبر الذكاء الاصطناعي - منصة الجدول الذكي",
                'dir': 'rtl'
            },
            'fr': {
                'republic': "République Algérienne Démocratique et Populaire",
                'ministry': "Ministère de l'Éducation Nationale",
                'teacher_title': "Emploi du temps du Professeur:",
                'class_title': "Emploi du temps de la Classe:",
                'season': "Année Scolaire : 2026 - 2027",
                'days': ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi"],
                'headers': ["Jours", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00"],
                'footer': "Généré automatiquement par l'IA - Plateforme JadwalAI",
                'dir': 'ltr'
            },
            'en': {
                'republic': "People's Democratic Republic of Algeria",
                'ministry': "Ministry of National Education",
                'teacher_title': "Teacher's Schedule:",
                'class_title': "Class Schedule:",
                'season': "Academic Year: 2026 - 2027",
                'days': ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"],
                'headers': ["Days", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00"],
                'footer': "Automatically generated by AI - JadwalAI Platform",
                'dir': 'ltr'
            }
        }
        self.t = self.texts.get(self.lang, self.texts['ar'])

    def _format_text(self, text):
        if not text: return ""
        text_str = str(text)
        
        # تنظيف الشوائب الناتجة عن محرك الـ PDF وإضافة مسافة حول الحرف لحماية الرقم (1م1)
        text_str = text_str.replace('?', '').replace('$', '').replace('_', '')
        text_str = text_str.replace('م', ' م ').replace('ث', ' ث ')
        
        lines = text_str.split('\n')
        processed = []
        for line in lines:
            reshaped = arabic_reshaper.reshape(line)
            # ضبط الاتجاه الصحيح للغة ليحافظ على الأقواس (كمال 2) بشكلها الطبيعي
            bidi_dir = 'R' if self.t['dir'] == 'rtl' else 'L'
            bidi_text = get_display(reshaped, base_dir=bidi_dir)
            processed.append(bidi_text)
            
        return '\n'.join(processed)

    def draw_text(self, c, text, x, y, font_size=12, align='right'):
        processed = self._format_text(text)
        c.setFont('Arabic', font_size)
        if align == 'right': c.drawRightString(x, y, processed)
        elif align == 'center': c.drawCentredString(x, y, processed)
        else: c.drawString(x, y, processed)

    def _draw_single_page(self, c, title_text, schedule_data, width, height):
        """رسم جدول واحد في الصفحة الحالية"""
        self.draw_text(c, self.t['republic'], width/2, height - 30, 14, 'center')
        self.draw_text(c, self.t['ministry'], width/2, height - 50, 14, 'center')
        
        if self.t['dir'] == 'rtl':
            self.draw_text(c, title_text, width - 50, height - 85, 16, 'right')
            self.draw_text(c, self.t['season'], 50, height - 85, 12, 'left')
        else:
            self.draw_text(c, title_text, 50, height - 85, 16, 'left')
            self.draw_text(c, self.t['season'], width - 50, height - 85, 12, 'right')

        data = []
        if self.t['dir'] == 'rtl': data.append([self._format_text(h) for h in reversed(self.t['headers'])])
        else: data.append([self._format_text(h) for h in self.t['headers']])
        
        for i, day_name_arabic in enumerate(["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس"]):
            day_hours = []
            for h in self.texts['ar']['headers'][1:]: 
                cell_text = schedule_data.get(day_name_arabic, {}).get(h, "")
                day_hours.append(self._format_text(cell_text))

            if self.t['dir'] == 'rtl':
                row = list(reversed(day_hours))
                row.append(self._format_text(self.t['days'][i]))
            else:
                row = [self._format_text(self.t['days'][i])] + day_hours
            data.append(row)

        col_widths = [85] * 8 + [100] if self.t['dir'] == 'rtl' else [100] + [85] * 8
        t = Table(data, colWidths=col_widths, rowHeights=45)
        
        style = [
            ('FONTNAME', (0,0), (-1,-1), 'Arabic'), ('FONTSIZE', (0,0), (-1,-1), 11),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'), ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 1, colors.black), ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1B4F72')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ]
        if self.t['dir'] == 'rtl': style.append(('BACKGROUND', (-1,1), (-1,-1), colors.whitesmoke))
        else: style.append(('BACKGROUND', (0,1), (0,-1), colors.whitesmoke))
        t.setStyle(TableStyle(style))

        t.wrapOn(c, width, height)
        t.drawOn(c, (width - sum(col_widths)) / 2, height - 420)
        self.draw_text(c, self.t['footer'], width/2, 30, 10, 'center')

    def generate_all_pdfs(self, teachers_schedules: dict, classes_schedules: dict):
        """يولد ملفين PDF: واحد لكل الأساتذة، وواحد لكل الأقسام"""
        w, h = landscape(A4)
        
        # 1. جداول الأساتذة
        teachers_filename = f"teachers_schedules_{self.lang}.pdf"
        tc = canvas.Canvas(os.path.join(self.job_dir, teachers_filename), pagesize=landscape(A4))
        for teacher, data in teachers_schedules.items():
            title = f"{self.t['teacher_title']} {teacher}"
            self._draw_single_page(tc, title, data, w, h)
            tc.showPage() # إنشاء صفحة جديدة للأستاذ التالي
        tc.save()

        # 2. جداول الأقسام
        classes_filename = f"classes_schedules_{self.lang}.pdf"
        cc = canvas.Canvas(os.path.join(self.job_dir, classes_filename), pagesize=landscape(A4))
        for class_name, data in classes_schedules.items():
            title = f"{self.t['class_title']} {class_name}"
            self._draw_single_page(cc, title, data, w, h)
            cc.showPage() # إنشاء صفحة جديدة للقسم التالي
        cc.save()

        return teachers_filename, classes_filename